# pg-tileserv Docker Compose example setup.
#
# To build/run, see README.md
#
version: "3"

services:
  pg_tileserv:
    image: pramsey/pg_tileserv:latest-alpine-3.12
    build:
      context: ../..
      dockerfile: Dockerfile.alpine
      args:
        VERSION: latest-alpine-3.12

    container_name: pg_tileserv

    volumes:
      - ./data:/data

    env_file:
      - pg_tileserv.env

    depends_on:
      - pg_tileserv_db

    ports:
      - 7800:7800

  pg_tileserv_db:
    image: postgis/postgis:13-3.0-alpine

    container_name: pg_tileserv_db

    volumes:
      - ./data:/work
      - pg_tileserv_db:/var/lib/postgresql/data

    env_file:
      - pg.env

    # expose ports for development
    #ports:
    #  - 5434:5432

  pg_gdal:
    image: osgeo/gdal:alpine-normal-latest-amd64

    container_name: pg_gdal

    command: tail -F /dev/null

    volumes:
      - ./data:/data

    depends_on:
      - pg_tileserv_db

  pg_static_tileserv:
    image: lipanski/docker-static-website:latest

    container_name: pg_static_tileserv

    volumes:
      - ./data/html:/home/static

    ports:
      - 3000:3000

    depends_on:
      - pg_tileserv_db

volumes:
  pg_tileserv_db:
